application:
  name: "safe-net-client"
  version: "1.0.0"

adapters:
  primary:
    server:
      port: ":8081"
  secondary:
    providers:
      serverProvider:
        host: "http://localhost:8080"
        endpoints:
          messages:
            method: "POST"
            path: "/api/v1/messages"
          send:
            method: "POST"
            path: "/api/v1/send"