application:
  name: "safe-net-client"
  version: "1.0.0"

adapters:
  primary:
    httpAdapter:
      server:
        port: ":8000"
  secondary:
    repositories:
      cache:
        filepath: "/bin/account.json"
    providers:
      serverProvider:
        host: "http://service-messages:3000"
        endpoints:
          get:
            method: "POST"
            path: "/api/v1/message/get"
          send:
            method: "POST"
            path: "/api/v1/message/save"
