version: '3.9'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "8081:8081"
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - app-network

  postgres:
    image: postgres:13.0
    environment:
      POSTGRES_DB: 'messages'
      POSTGRES_USER: 'messages-user'
      POSTGRES_PASSWORD: '123457890'
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge