version: '3.9'

services:

  client:
    build:
      context: ./client/deploy
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "8001:8001"
    networks:
      - app-network

  server:
    build:
      context: ./server/deploy
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - app-network

  postgres:
    image: postgres:13.0
    environment:
      POSTGRES_DB: 'myDb'
      POSTGRES_USER: 'myUser'
      POSTGRES_PASSWORD: 'myPassword'
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge