openapi: 3.0.3
info:
  title: SAFE.NET Server
  description: API Documentation for SAFE.NET endpoints
  version: v1.0.0
servers:
  - url: 'https://localhost:8000'
paths:
  /api/v1/user:
    get:
      tags:
        - "Получение информации о юзере"
      responses:
        '200':
          description: "OK"
        default:
          description: "Error"
  
