application:
  name: "safe-net-server"
  version: "1.0.0"

adapters:
  primary:
    server:
      port: ":8080"
  secondary:
    databases:
      messages:
        host: "host"
        port: "port"
        type: "postgres"
        name: "messages"
        user: "messages-user"
        password: "messages-password"
        procedures:
          getMessages: "messages.get_messages"
          saveMessage: "messages.save_message"